apiVersion: v1
kind: Service
metadata:
 name: nerddinner-svc
 labels:
   app: nerddinner-svc
spec:
 ports:
   # the port that this service should serve on
 - port: 80
   targetPort: 80
 selector:
   app: win-nerddinner
 type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: win-nerddinner
  name: win-nerddinner
spec:
  selector:
    matchLabels:
      app: win-nerddinner
  replicas: 1
  template:
    metadata:
      labels:
        app: win-nerddinner
      name: win-nerddinner
    spec:
      tolerations:
      - key: "os"
        value: "Windows"
        Effect: "NoSchedule"
      containers:
      - name: windowsnerddinner
        image: quay.io/xphyr/nerddinner-ocp:ltsc2022-latest
        imagePullPolicy: IfNotPresent
        startupProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /
            port: 80
        env:
        - name: CONNSTR_DefaultConnection
          valueFrom:
            secretKeyRef:
              name: nerddinnersecret
              key: DEFAULT_CONNECTION
        - name: CONNSTR_NerdDinnerContext
          valueFrom:
            secretKeyRef:
              name: nerddinnersecret
              key: NERDDINNER_CONTEXT
        - name: APPSETTING_BingMapsKey
          valueFrom:
            secretKeyRef:
              name: nerddinnersecret
              key: BING_MAPS_KEY
      nodeSelector:
        kubernetes.io/os: windows